### ISSUE TITLE
Crash at Revolutions.RevolutionManager.IncreaseDailyLoyaltyForSettlement()

### ISSUE THREAD

**Issue by Solganis** [TH3UNKN0WN-1337/Bannerlord#1]
1.4 Beta
Just sitting in my castle and getting this crash.

Source: Revolutions
Object reference not set to an instance of an object.

at Revolutions.Components.Revolutions.RevolutionManager.IncreaseDailyLoyaltyForSettlement()
at Revolutions.CampaignBehaviors.RevolutionDailyBehavior.DailyTickEvent()
at TaleWorlds.CampaignSystem.MbEvent.InvokeList(EventHandlerRec list)
at TaleWorlds.CampaignSystem.CampaignEvents.DailyTick()
at TaleWorlds.CampaignSystem.CampaignEventDispatcher.DailyTick()
at TaleWorlds.CampaignSystem.Campaign.DailyTick(MBCampaignEvent campaignEvent, Object[] delegateParams)
at TaleWorlds.CampaignSystem.MBCampaignEvent.RunHandlers(Object[] delegateParams)
at TaleWorlds.CampaignSystem.MBCampaignEvent.CheckUpdate(Single curTime)
at TaleWorlds.CampaignSystem.CampaignEvents.SignalPeriodicEvents()
at TaleWorlds.CampaignSystem.Campaign.Tick(Single dt)
at TaleWorlds.CampaignSystem.Campaign.RealTick(Single realDt)
at TaleWorlds.CampaignSystem.MapState.OnMapModeTick(Single dt)
at TaleWorlds.Core.GameStateManager.OnTick(Single dt)
at TaleWorlds.Core.Game.OnTick(Single dt)
at TaleWorlds.Core.GameManagerBase.OnTick(Single dt)
at DMD?66083951::OnApplicationTick_Patch1>(Module this, Single dt)

**Comment by TH3UNKN0WN-1337** [comment]
Hi, sorry that I wasn't aware of our Issues section. This error shoud be fixed with 0.5.0 RC1.
